services:
  argo-nezha-v1:
    image: yutian81/argo-nezha-v1:latest
    container_name: argo-nezha-v1
    restart: unless-stopped
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./dashboard:/dashboard/data
